import boto3
import json

def add_data_in_DynamoTable(table_name):
    try:
        dynamodb_client = boto3.client('dynamodb', region_name='us-west-2')
        response = dynamodb_client.put_item(
            TableName = table_name,
            Item={
                'UserId': {'S': 'kuldeep'},
                'Branch': {'S': 'N Veriginia'},
                'Skills': {'S': 'Presentation'},
                'UserId': {'S': 'Anchal'},
                'Branch': {'S': 'Oregon'},
                'Skills': {'S': 'Backend'},
                'UserId': {'S': 'Gungun'},
                'Branch': {'S': 'Ohio'},
                'Skills': {'S': 'Modling'},
                'UserId': {'S': 'Surbhi'},
                'Branch': {'S': 'N California'},
                'Skills': {'S': 'NULL'}
            }
        )
        print(f"The item were added in the {table_name} in dynamoDB Table.")
    except Exception as e :
        print(f"The error has been occured while adding data in the table {table_name}", e)

if __name__ == '__main__':
    try:
        table_name = 'dbTable'
        add_data_in_DynamoTable(table_name)
    except Exception as e:
        print("An error occured while reading the table name", e)

